[package]
name = "rdkafka_v028_simple"
version = "0.1.0"
edition = "2021"
build   = "build.rs"

[dependencies]
rdkafka = { version = "0.28", features = ["cmake-build","ssl", "sasl"] }

[[bin]]
name = "producer"
path = "src/producer.rs"

[[bin]]
name = "consumer"
path = "src/consumer.rs"