[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3

[package]
  authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
  build   = "build.rs"
  edition = "2024"
  name    = "rdkafka_v028_simple"
  version = "0.1.0"

[dependencies]
  rdkafka = {version = "0.32.2", features = ["cmake-build", "sasl", "ssl"]}

[[bin]]
  name = "producer"
  path = "src/producer.rs"

[[bin]]
  name = "consumer"
  path = "src/consumer.rs"
