[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[package]
name = "async_graphql_v5"
version = "0.1.0"
authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
edition = "2021"

[dependencies]
async-graphql = "5.0"
async-graphql-actix-web = "5.0"
actix-web = "4.3"
