[package]
name = "async_graphql_v5_with_diesel_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "5.0"
async-graphql-actix-web = "5.0"
actix-web = "4.3"

diesel = { version = "2.0.3", features = ["postgres"] }

dotenv = "0.15"

