[package]
name = "async_graphql_v5_with_diesel_v2"
version = "0.1.0"
authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.3.1"
async-graphql = "5.0.10"
async-graphql-actix-web = "5.0.10"
diesel = { version = "2.1.0", features = ["postgres"] }
dotenv = "0.15.0"