[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3

[package]
  authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
  edition = "2024"
  name    = "wasm-lib"
  version = "0.1.0"

[lib]
  crate-type = ["cdylib"]

[dependencies]
  wasm-bindgen = "0.2.95"
