[package]
  edition = "2021"
  name    = "rocket_surreal"
  version = "0.1.0"

[dependencies]
  faker_rand = "0.1.1"
  rand       = "0.8.5"
  rocket     = {version = "0.5.1", features = ["json"]}
  serde      = {version = "1.0.214", features = ["derive"]}
  surrealdb  = "2.2.2"
  thiserror  = "2.0.12"
  tokio      = {version = "1.44.2", features = ["full"]}
