# Stable options
edition   = "2021"
max_width = 200

# Unstable options
format_code_in_doc_comments = true
format_strings              = true
group_imports               = "One"
imports_granularity         = "Crate"
