[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[package]
name = "check_date"
version = "1.0.0"
edition = "2021"


[dependencies]
regex = "1.11.1"
time = "0.3.36"
