[workspace]
members = [
    "domain",
    "application", 
    "infrastructure",
    "presentation-frontend",
    "presentation-backend"
]
resolver = "2"

# Shared dependencies for all workspace members
[workspace.dependencies]
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }