# Disable workspace mode to avoid task resolution issues
[config]
  skip_core_tasks     = false
  skip_crate_env_info = false
  skip_git_env_info   = false
  skip_rust_env_info  = false

[env]
  CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "true"

[tasks.clean]
  args    = ["clean"]
  command = "cargo"

[tasks.clippy]
  args    = ["clippy"]
  command = "cargo"

[tasks.check]
  args    = ["check"]
  command = "cargo"

[tasks.format]
  args          = ["fmt"]
  command       = "cargo"
  dependencies  = ["check", "clippy"]
  install_crate = "rustfmt"

[tasks.build]
  args         = ["build", "--profile", "dev"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.release]
  args         = ["build", "--profile", "release"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.test]
  args         = ["test"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.watch-run]
  # `cargo install cargo-watch`로 설치
  args          = ["watch", "-x", "tauri dev"]
  command       = "cargo"
  dependencies  = ["format"]
  install_crate = "cargo-watch"

[tasks.run]
  args          = ["tauri", "dev"]
  command       = "cargo"
  dependencies  = ["format"]
  install_crate = "tauri-cli"
  workspace     = false
