[package]
name = "database-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
