[package]
name = "infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "uuid", "chrono"] }
async-trait = "0.1"
uuid = { version = "1.0", features = ["v4"] }
tokio = { version = "1.0", features = ["full"] }