[formatting]
  align_comments        = true
  align_entries         = true
  array_auto_collapse   = false
  column_width          = 80
  compact_arrays        = true
  compact_inline_tables = true
  indent_entries        = true
  indent_tables         = true
  inline_table_expand   = false
  reorder_arrays        = false
  reorder_inline_tables = true
  reorder_keys          = true
