[tasks.clean]
  args    = ["clean"]
  command = "cargo"

[tasks.clippy]
  args    = ["clippy"]
  command = "cargo"

[tasks.check]
  args    = ["check"]
  command = "cargo"

[tasks.format]
  args          = ["fmt"]
  command       = "cargo"
  dependencies  = ["check", "clippy"]
  install_crate = "rustfmt"

[tasks.build]
  args         = ["build", "--workspace"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.build-gui]
  args         = ["build", "-p", "app-gui"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.release]
  args         = ["build", "--release", "--workspace"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.release-gui]
  args         = ["build", "-p", "app-gui", "--release"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.test]
  args         = ["test", "--workspace"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.test-plugin-manager]
  args         = ["test", "-p", "plugin-manager"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.test-integration]
  args         = ["test", "-p", "plugin-manager", "--test", "integration_test"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.watch-run]
  # `cargo install cargo-watch`로 설치
  args          = ["watch", "-x", "run -p app-gui"]
  command       = "cargo"
  dependencies  = ["format"]
  install_crate = "cargo-watch"
  run_task      = {name = "empty"}
  workspace     = false

[tasks.run]
  args         = ["run", "-p", "app-gui"]
  command      = "cargo"
  dependencies = ["format"]
  workspace    = false

[tasks.run-release]
  args         = ["run", "-p", "app-gui", "--release"]
  command      = "cargo"
  dependencies = ["format"]
  workspace    = false
