[package]
  authors.workspace = true
  edition.workspace = true
  name              = "collection-exists"
  version.workspace = true

[dependencies]
  dotenv        = "0.15.0"
  qdrant-client = {features = ["serde"], version = "1.15.0"}
  tokio         = {features = ["full"], version = "1.47.1"}

[[example]]
  name = "basic-usage"
  path = "examples/basic-usage.rs"
