[package]
  edition = "2024"
  name    = "lib-index"
  version = "0.1.0"

[dependencies]
  anyhow     = "1.0"
  log        = "0.4"
  regex      = "1.10"
  serde      = {features = ["derive"], version = "1.0"}
  serde_json = "1.0"
  thiserror  = "2.0"
  # SurrealDB는 lib-db를 통해 사용
  lib-db = {path = "../lib-db", version = "0.1.0"}

  # 임베딩(TF-IDF)용
  hashbrown = "0.14"

  # PDF 파싱(향후 실제 파서로 교체 가능). 현재는 간단한 텍스트 추출 스텁 포함

[features]
  default = []
  # Windows/macOS에서 PDFium DLL 필요
  lopdf  = ["dep:lopdf"]
  pdfium = ["dep:pdfium-render"]

  [dependencies.pdfium-render]
    optional = true
    version  = "0.8"

  [dependencies.lopdf]
    optional = true
    version  = "0.31"
