[profile.dev]
  codegen-units = 256
  debug         = true
  incremental   = true
  opt-level     = 1

[profile.release]
  codegen-units = 1
  debug         = false
  lto           = "thin"
  opt-level     = 3

[package]
  edition = "2024"
  name    = "p20_custom_error_types"
  version = "0.1.0"


[dependencies]
  thiserror = "2.0.0"

[[bin]]
  name = "main"
  path = "src/main.rs"
