[package]
  edition = "2024"
  name    = "bin-main"
  version = "0.1.0"

[dependencies]
  actix-web  = "4.9.0"
  dotenvy    = "0.15.7"
  env_logger = "0.11.5"
  lib-api    = {path = "../lib-api", version = "0.1.0"}
