[application]

# =====================
# Web (WASM) settings
# =====================
[web.app]
  # HTML title tag content
  title = "dioxus-app"

[web.resource]
  # Additional CSS style files
  style = []
  # Additional JavaScript files
  script = []

  [web.resource.dev]
    # Javascript code file
    # serve: [dev-server] only
    script = []

[web]
  # Output dir for web build
  out_dir = "dist"
  # Public URL base (for GitHub Pages, etc)
  public_url = "/"
  # Dev server port
  port = 8080
