[package]
  edition = "2021"
  name    = "actix_lib"
  version = "0.1.0"

[dependencies]
  actix-web     = "4.9.0"
  log           = "0.4.22"
  surrealdb_lib = {version = "0.1.0", path = "../surrealdb_lib"}
