[tasks.clean]
command = "cargo"
args = ["clean"]
workspace = false

[tasks.clippy]
command = "cargo"
args = ["clippy", "--workspace", "--all-targets"]
workspace = false

[tasks.check]
command = "cargo"
args = ["check", "--workspace"]
workspace = false

[tasks.format]
command = "cargo"
args = ["fmt", "--all"]
workspace = false

[tasks.build]
command = "cargo"
args = ["build", "--workspace"]
workspace = false

[tasks.release]
command = "cargo"
args = ["build", "--workspace", "--release"]
workspace = false

[tasks.test]
command = "cargo"
args = ["test", "--workspace"]
workspace = false

[tasks.test-domain]
command = "cargo"
args = ["test", "-p", "domain"]
workspace = false

[tasks.test-application]
command = "cargo"
args = ["test", "-p", "application"]
workspace = false

[tasks.test-infrastructure]
command = "cargo"
args = ["test", "-p", "infrastructure"]
workspace = false

[tasks.run]
description = "Run the Tauri application in development mode"
cwd = "presentation_backend"
command = "cargo"
args = ["tauri", "dev"]
workspace = false

[tasks.dev]
description = "Alias for run task"
alias = "run"

[tasks.build-app]
description = "Build the Tauri application for production"
cwd = "presentation_backend"
command = "cargo"
args = ["tauri", "build"]
workspace = false
