[toolchain]
  channel = "nightly"
  components = [
    "cargo-generate",
    "cargo-leptos",
    "clippy",
    "leptosfmt",
    "rust-analyzer",
    "rust-src",
    "rustfmt",
    "trunk",
  ]
  profile = "default"
