[package]
name = "domain"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
# Domain layer has NO dependencies on other layers
# Only external libraries for basic types
serde.workspace = true
chrono.workspace = true
uuid.workspace = true
thiserror.workspace = true
async-trait.workspace = true
