[package]
  authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
  edition = "2024"
  name    = "async_graphql_v7_splitted_code"
  version = "0.1.0"

[dependencies]
  actix-web               = "4.9.0"
  async-graphql           = "7.0"
  async-graphql-actix-web = "7.0"
  diesel                  = {version = "2.2.5", features = ["postgres"]}

[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3
