[package]
  edition = "2024"
  name    = "lib-db"
  version = "0.1.0"

[dependencies]
  anyhow    = "1.0.95"
  log       = "0.4.22"
  surrealdb = "2.1.2"
  tokio     = {features = ["time"], version = "1.40.0"}
