version: '3'

services:
  postgres:
    image: postgres:17.6
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clean_architecture
    ports:
      - "5432:5432"
