[tasks.clean]
  args    = ["clean"]
  command = "cargo"

[tasks.clippy]
  args    = ["clippy"]
  command = "cargo"

[tasks.check]
  args    = ["check"]
  command = "cargo"

[tasks.format]
  args          = ["fmt"]
  command       = "cargo"
  dependencies  = ["check", "clippy"]
  install_crate = "rustfmt"

[tasks.build]
  args         = ["build", "--all-features"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.release]
  args         = ["build", "--release", "--all-features"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.test]
  args         = ["test"]
  command      = "cargo"
  dependencies = ["format"]

# src-tauri는 백엔드이므로 직접 실행하지 않고 빌드만 수행
[tasks.run]
  dependencies = ["build"]