[profile.dev]
  codegen-units = 256
  debug         = true
  incremental   = true
  opt-level     = 1

[profile.release]
  codegen-units = 1
  debug         = false
  lto           = "thin"
  opt-level     = 3

[package]
  authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
  build   = "build.rs"
  edition = "2024"
  name    = "rdkafka-v028-simple"
  version = "0.1.0"

[dependencies]
  rdkafka = {version = "0.32.2", features = ["cmake-build", "sasl", "ssl"]}

[[bin]]
  name = "producer"
  path = "src/producer.rs"

[[bin]]
  name = "consumer"
  path = "src/consumer.rs"
