[package]
  edition = "2024"
  name    = "backend"
  version = "0.1.0"

[dependencies]
  actix-web = "4.9.0"
  actix-files = "0.6.6"
  clap      = {version = "4.5.20", features = ["derive"]}
  serde_json = "1.0"
  chrono = {version = "0.4", features = ["serde"]}
