[package]
  edition = "2024"
  name    = "backend"
  version = "0.1.0"

[dependencies]
  actix-files = "0.6.6"
  actix-web   = "4.9.0"
  async-trait = "0.1"
  chrono      = {features = ["serde"], version = "0.4"}
  clap        = {features = ["derive"], version = "4.5.20"}
  serde       = {features = ["derive"], version = "1.0"}
  serde_json  = "1.0"
  sqlx        = {features = ["runtime-tokio-rustls", "sqlite", "chrono", "uuid"], version = "0.7"}
  tokio       = {features = ["full"], version = "1.0"}
  uuid        = {features = ["v4", "serde"], version = "1.0"}
