[package]
  authors = ["my-name <my-email@address.com>"]
  edition = "2021"
  name    = "my-api"
  version = "0.1.0"

[dependencies]
  console_error_panic_hook = "0.1"
  console_log              = "1"
  leptos                   = {version = "0.6", features = ["csr", "nightly"]}
  leptos_meta              = {version = "0.6", features = ["csr", "nightly"]}
  leptos_router            = {version = "0.6", features = ["csr", "nightly"]}
  log                      = "0.4"
  gloo-timers = { version = "0.2", features = ["futures" ]}

[dev-dependencies]
  wasm-bindgen      = "0.2"
  wasm-bindgen-test = "0.3"
  web-sys           = {version = "0.3", features = ["Document", "Window"]}


[profile.release]
  codegen-units = 1
  lto           = true
  opt-level     = 'z'
  panic         = "abort"
