[package]
  edition = "2024"
  name    = "web_crawler"
  version = "0.1.0"

[dependencies]
  reqwest = {version = "0.12.4", features = ["blocking", "json"]}
  select  = "0.6.0"
  tokio   = {version = "1.44.2", features = ["full"]}
