binop_separator                = "Front"
color                          = "Always"
doc_comment_code_block_width   = 80
edition                        = "2024"
enum_discrim_align_threshold   = 40
fn_params_layout               = "Tall"
fn_single_line                 = true
format_code_in_doc_comments    = true
format_strings                 = false
group_imports                  = "One"
imports_granularity            = "Module"
imports_indent                 = "Visual"
imports_layout                 = "Horizontal"
match_arm_blocks               = false
match_arm_leading_pipes        = "Always"
match_block_trailing_comma     = true
max_width                      = 160
newline_style                  = "Unix"
normalize_comments             = true
normalize_doc_attributes       = true
reorder_impl_items             = true
reorder_imports                = true
single_line_let_else_max_width = 0
spaces_around_ranges           = true
struct_lit_single_line         = false
style_edition                  = "2024"
use_try_shorthand              = true
wrap_comments                  = true
#chain_width                    = 0
#control_brace_style            = "ClosingNextLine"
#fn_args_layout                 = "Tall"
#indent_style                   = "Visual"
#struct_field_align_threshold   = 40
#trailing_comma                 = "Always"
