[package]
  edition = "2024"
  name    = "main"
  version = "0.1.0"

[dependencies]
  domain      = {path = "../domain"}
  application = {path = "../application"}
  adapters    = {path = "../adapters"}
  infra       = {path = "../infra"}
  pq-sys      = {version = "0.6", features = ["bundled"]}
  openssl-sys = {version = "0.9", features = ["vendored"]}
