[package]
  edition = "2024"
  name    = "main"
  version = "0.1.0"

[dependencies]
  domain      = {path = "../domain", features = ["serde"]}
  application = {path = "../application"}
  adapters    = {path = "../adapters"}
  infra       = {path = "../infra"}
  diesel      = {workspace = true}
  axum        = {workspace = true}
  tokio       = {workspace = true}
  tower       = {workspace = true}
  tower-http  = {workspace = true}
  serde       = {workspace = true}
  serde_json  = {workspace = true}
