[package]
  edition = "2024"
  name    = "main"
  version = "0.1.0"

[dependencies]
  adapters    = {path = "../adapters"}
  application = {path = "../application"}
  axum        = {workspace = true}
  diesel      = {workspace = true}
  domain      = {features = ["serde"], path = "../domain"}
  infrastructure       = {path = "../infrastructure"}
  serde       = {workspace = true}
  serde_json  = {workspace = true}
  tokio       = {workspace = true}
  tower       = {workspace = true}
  tower-http  = {workspace = true}
