[package]
name = "diesel_sqlite_init"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15.7"

[dependencies.rusqlite]
version = "0.29.0"
features = ["bundled"]

[[bin]]
name = "show"
path = "src/bin/show_posts.rs"

[[bin]]
name = "write"
path = "src/bin/write_post.rs"

[[bin]]
name = "publish"
path = "src/bin/publish_post.rs"

[[bin]]
name = "delete"
path = "src/bin/delete_post.rs"