[package]
name = "application"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
# Application layer depends ONLY on domain layer
domain = { path = "../domain" }

# External dependencies
async-trait.workspace = true
uuid.workspace = true
