arrowParens: always
bracketSpacing: true
endOfLine: lf
jsxBracketSameLine: true
printWidth: 120
semi: true
singleQuote: true
tabWidth: 2
tabs: false
trailingComma: es5
plugins:
  - prettier-plugin-organize-attributes
  - prettier-plugin-organize-imports
  - prettier-plugin-tailwindcss
tailwindConfig: ./tailwind.config.js
