max_width = 150
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
combine_control_expr = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2021"
empty_item_single_line = true
enum_discrim_align_threshold = 80
error_on_unformatted = true
fn_args_layout = "Tall"
force_multiline_blocks = false
format_code_in_doc_comments = true
format_strings = false
hard_tabs = false
imports_indent = "Visual"
imports_layout = "Vertical"
indent_style = "Visual"
inline_attribute_width = 0
merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
struct_field_align_threshold = 20
struct_lit_single_line = false
tab_spaces = 2
trailing_comma = "Always"
trailing_semicolon = true
type_punctuation_density = "Compressed"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true