[package]
name = "presentation_backend"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "A Tauri App"

[lib]
name = "presentation_backend_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
# Presentation layer can depend on all lower layers
domain = { path = "../domain" }
application = { path = "../application" }
infrastructure = { path = "../infrastructure" }

# Tauri and web framework dependencies
tauri.workspace = true
tauri-plugin-opener.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true
anyhow.workspace = true
