networks:
  docker-link:
    external: true

services:
  surrealdb:
    image: "surrealdb/surrealdb:latest"
    container_name: surrealdb
    command: 
      - start
      - --log=trace
      - --user=${SURREALDB_USERNAME}
      - --pass=${SURREALDB_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SURREALDB_URL=localhost:8000
      - SURREALDB_USERNAME=root
      - SURREALDB_PASSWORD=root
      - SURREALDB_NS=namespace
      - SURREALDB_DB=database
    networks:
      - docker-link
