[package]
name = "plugin-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
plugin-interface = { path = "../plugin-interface" }
anyhow = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }
libloading = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
