[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[package]
name = "juniper_v014_mysql"
version = "2.0.0"
authors = ["mingyuchoo <mingyuchoo@gmail.com>"]
edition = "2021"


[dependencies]
actix-web = "3"
juniper = "0.14"
mysql = "20.1"
r2d2 = "0.8"
r2d2_mysql = "23.0"
dotenv = "0.15"
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
openssl = { version = "0.10", features = ["vendored"] }
