[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3

[package]
  authors = ["mingyuchoo <mingyuchoo@gmail.com>"]
  edition = "2021"
  name    = "juniper_v014_mysql"
  version = "2.0.0"


[dependencies]
  actix-web  = "3"
  dotenv     = "0.15"
  env_logger = "0.10"
  juniper    = "0.14"
  log        = "0.4"
  mysql      = "20.1"
  openssl    = {version = "0.10", features = ["vendored"]}
  r2d2       = "0.8"
  r2d2_mysql = "23.0"
  serde      = {version = "1.0", features = ["derive"]}
  serde_json = "1.0"
  uuid       = {version = "0.8", features = ["serde", "v4"]}
