binop_separator                = "Front"
chain_width                    = 0
color                          = "Always"
control_brace_style            = "ClosingNextLine"
doc_comment_code_block_width   = 80
edition                        = "2021"
enum_discrim_align_threshold   = 40
fn_params_layout               = "Vertical"
format_code_in_doc_comments    = true
format_strings                 = false
group_imports                  = "One"
imports_granularity            = "Module"
imports_indent                 = "Visual"
imports_layout                 = "Horizontal"
indent_style                   = "Visual"
match_arm_leading_pipes        = "Always"
match_block_trailing_comma     = true
max_width                      = 80
newline_style                  = "Unix"
normalize_comments             = true
normalize_doc_attributes       = true
reorder_impl_items             = true
reorder_imports                = true
single_line_let_else_max_width = 0
spaces_around_ranges           = true
struct_field_align_threshold   = 40
struct_lit_single_line         = false
trailing_comma                 = "Always"
use_try_shorthand              = true
wrap_comments                  = true
