[package]
  edition = "2021"
  name    = "egui-surreal"
  version = "0.1.0"

[dependencies]
  anyhow     = "1.0.93"
  eframe     = "0.29.1"
  egui       = "0.29.1"
  faker_rand = "0.1.1"
  rand       = "0.8.5"
  serde      = {version = "1.0.214", features = ["derive"]}
  serde_json = "1.0.132"
  surrealdb  = "2.0.4"
  tokio      = {version = "1.41.1", features = ["full"]}
