[workspace]
  members  = ["persistence", "domain", "application", "adapters", "infra", "runner"]
  resolver = "2"
  [workspace.dependencies]
    diesel  = {version = "2.3.2", features = ["postgres"]}
    dotenvy = "0.15.7"
