[tasks.clean]
  args    = ["clean"]
  command = "cargo"

[config]
  default_to_workspace = false

[tasks.clippy]
  args    = ["clippy"]
  command = "cargo"

[tasks.check]
  args    = ["check"]

[tasks.format]
  args          = ["fmt"]
  command       = "cargo"
  dependencies  = ["check", "clippy"]
  install_crate = "rustfmt"

[tasks.build]
  args         = ["build", "--profile", "dev"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.release]
  args         = ["build", "--profile", "release"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.test]
  args         = ["test"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.watch-run]
  # `cargo install cargo-watch`로 설치
  args          = ["watch", "-x", "run"]
  command       = "cargo"
  dependencies  = ["format"]
  install_crate = "cargo-watch"

[tasks.run]
  args         = ["run"]
  command      = "cargo"
  dependencies = ["format"]

# Docker Compose helpers
[tasks.docker-compose-up]
  args    = ["compose", "-f", "docker/docker-compose.yaml", "up", "-d", "--build"]
  command = "docker"

[tasks.docker-compose-down]
  args    = ["compose", "-f", "docker/docker-compose.yaml", "down"]
  command = "docker"

[tasks.docker-compose-logs]
  args = [
    "compose",
    "-f",
    "docker/docker-compose.yaml",
    "logs",
    "-f",
    "--tail",
    "200",
  ]
  command = "docker"

[tasks.docker-compose-logs-app]
  args    = ["compose", "-f", "docker/docker-compose.yaml", "logs", "-f", "app"]
  command = "docker"

[tasks.docker-compose-ps]
  args    = ["compose", "-f", "docker/docker-compose.yaml", "ps"]
  command = "docker"

[tasks.docker-compose-restart]
  args    = ["compose", "-f", "docker/docker-compose.yaml", "restart", "app"]
  command = "docker"
