[config]
  default_to_workspace = true
  skip_core_tasks = true

[env]
  APP_PACKAGE = "webcam-detector"

[tasks.default]
  clear        = true
  dependencies = ["ci"]

[tasks.ci]
  dependencies = ["format", "check", "clippy", "test"]

[tasks.clean]
  args    = ["clean"]
  command = "cargo"

[tasks.format]
  args    = ["fmt", "--all"]
  command = "cargo"

[tasks.format-check]
  args    = ["fmt", "--all", "--check"]
  command = "cargo"

[tasks.clippy]
  args    = ["clippy", "--workspace", "--all-targets", "--all-features"]
  command = "cargo"

[tasks.check]
  args    = ["check", "--workspace", "--all-targets", "--all-features"]
  command = "cargo"

[tasks.build]
  args         = ["build", "--workspace", "--profile", "dev", "--all-features"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.release]
  args         = ["build", "--release", "-p", "${APP_PACKAGE}"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.test]
  args         = ["test", "--workspace", "--all-targets", "--all-features"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.watch-run]
  args          = ["watch", "-x", "run -p ${APP_PACKAGE}"]
  command       = "cargo"
  install_crate = "cargo-watch"
  workspace     = false

[tasks.run]
  args      = ["run", "-p", "${APP_PACKAGE}"]
  command   = "cargo"
  workspace = false
