[package]
name = "p03_guessing_game"
version = "0.1.0"
authors = ["mingyuchoo <mingyuchoo@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.1"