[package]
name = "presentation-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
console_error_panic_hook = "0.1.7"
js-sys = "0.3"
leptos = { version = "0.7", features = ["csr"] }
serde = { workspace = true }
serde-wasm-bindgen = "0.6"
serde_json = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
uuid = { workspace = true }