AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: rust-sam-app
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
    Runtime: provided.al2
    Architectures:
      - x86_64
  Api:
    TracingEnabled: true
Resources:
  PostHelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: post_hello_world_function
    Properties:
      CodeUri: ./rust_app
      Handler: bootstrap
      Events:
        PostHelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: post
  GetHelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: get_hello_world_function
    Properties:
      CodeUri: ./rust_app
      Handler: bootstrap
      Events:
        GetHelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  PostHelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  PostHelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PostHelloWorldFunction.Arn
  PostHelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PostHelloWorldFunctionRole.Arn
  GetHelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GetHelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GetHelloWorldFunction.Arn
  GetHelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GetHelloWorldFunctionRole.Arn
