[debug]
  address    = "127.0.0.1"
  cli_colors = true
  log_level  = "debug"
  port       = 4000
  secret_key = "zNhtNYqIZuFkcq+QTdxJno7SLDYf+gTpWq9Ytb0Jhdo="

  #[release]
  #port = 4000
  #address = "0.0.0.0"
  #log_level = "critical"
  #ip_header = false
  #secret_key = "zNhtNYqIZuFkcq+QTdxJno7SLDYf+gTpWq9Ytb0Jhdo="
