[package]
  authors.workspace = true
  edition.workspace = true
  name              = "create-collection"
  version.workspace = true

[dependencies]
  qdrant-client = {features = ["serde"], version = "1.15.0"}
  tokio = {version = "1.0", features = ["full"]}
  dotenvy = "0.15"

[[example]]
name = "basic-usage"
path = "examples/basic-usage.rs"