[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
plugin-manager = { path = "../plugin-manager" }
database-manager = { path = "../database-manager" }
plugin-interface = { path = "../plugin-interface" }
text-converter = { path = "../plugins/text-converter" }
eframe = { workspace = true }
egui = { workspace = true }
rfd = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
chrono = { workspace = true }
