[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[package]
name = "p02_hello_cargo"
version = "0.1.0"
authors = ["mingyuchoo <mingyuchoo@gmail.com>"]
edition = "2021"

[dependencies]
