[workspace]
members = [
    "plugin-manager",
    "plugin-interface",
    "database",
    "gui",
    "plugins/text-converter",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
# 공통 의존성
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# GUI
eframe = "0.28"
egui = "0.28"
rfd = "0.15"

# Database
rusqlite = { version = "0.31", features = ["bundled"] }

# 플러그인 관련
libloading = "0.8"

# 유틸리티
log = "0.4"
env_logger = "0.11"

# 텍스트 인코딩
encoding_rs = "0.8"
