[application]
  default_platform = "web"
  name             = "presentation_frontend"

[web.app]
  title = "주소록 앱"

[web.watcher]

[web.resource]
  style = ["/assets/styles.css"]

  [web.resource.dev]

[bundle]
  icon       = ["assets/dioxus.png"]
  identifier = "com.addressbook.app"
  publisher  = "Address Book"
  resources  = ["assets/*"]
