[application]
name = "presentation_frontend"
default_platform = "web"

[web.app]
title = "주소록 앱"

[web.watcher]

[web.resource]
style = ["/assets/styles.css"]

[web.resource.dev]

[bundle]
identifier = "com.addressbook.app"
publisher = "Address Book"
icon = ["assets/dioxus.png"]
resources = ["assets/*"]
