[package]
  edition = "2024"
  name    = "infrastructure"
  version = "0.1.0"

[dependencies]
  diesel            = {workspace = true}
  diesel_migrations = "2.1.0"
  dotenvy           = {workspace = true}
