[package]
name = "egui-app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.0"
egui_extras = { version = "0.28.0", features = ["all_loaders"] }
env_logger = "0.11.3"
image = { version = "0.25.1", features = ["jpeg", "png"] }
