[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3

[package]
  authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
  edition = "2024"
  name    = "rust"
  version = "0.1.0"

[lib]
  crate-type = ["cdylib"]
  patch      = "src/lib.rs"

[dependencies]
