[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[package]
name = "rust"
version = "0.1.0"
authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
edition = "2021"

[lib]
patch = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
