[package]
name = "diesel_mysql_init"
version = "0.1.0"
authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.0", features = ["mysql"] }
dotenvy = "0.15.7"

[[bin]]
doc = false
name = "show_posts"

[lib]
doc = false
