[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[package]
name = "diesel_mysql_init"
version = "0.1.0"
authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
edition = "2021"


[dependencies]
diesel = { version = "2.1.4", features = ["mysql"] }
dotenvy = "0.15.7"

[[bin]]
doc = false
name = "show_posts"

[lib]
doc = false
