[package]
edition = "2024"
name    = "korean-ls-demo"
version = "0.1.0"

[[bin]]
name = "korean-language-server"
path = "src/main.rs"

[dependencies]
regex      = "1.12.2"
serde_json = "1.0.145"
tokio      = {features = ["full"], version = "1.48.0"}
tower-lsp  = "0.20.0"
