services:
  postgres:
    image: postgres:17.6
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: axum-sqlx-postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/axum-sqlx-postgres
      JWT_SECRET: ${JWT_SECRET:-dev_change_me}
      RUST_LOG: axum-sqlx-postgres=debug,tower_http=debug,sqlx=warn
    ports:
      - "8000:8000"
    restart: unless-stopped
