[package]
  edition = "2024"
  name    = "demo-axum"
  version = "0.1.0"

[dependencies]
  axum  = "0.7.5"
  clap  = {version = "4.5.20", features = ["derive"]}
  tokio = {version = "1.44.2", features = ["full"]}
