[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3

[package]
  authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
  edition = "2021"
  name    = "async_graphql_v4_splitted_code"
  version = "0.1.0"

[dependencies]
  actix-web               = "4.3"
  async-graphql           = "5.0"
  async-graphql-actix-web = "5.0"

  diesel = {version = "2.0.3", features = ["postgres"]}
