[package]
  authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
  edition = "2024"
  name    = "simple_RPC"
  version = "0.1.0"

[[bin]]
  name = "server"
  path = "src/server.rs"

[[bin]]
  name = "client"
  path = "src/client.rs"

[dependencies]
  prost       = "0.13.5"
  prost-types = "0.13.5"
  tokio       = {version = "1.44.2", features = ["macros", "rt-multi-thread"]}
  tonic       = "0.13.0"

[build-dependencies]
  tonic-build = "0.13.0"

[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3
