[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3

[package]
  authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
  edition = "2021"
  name    = "simple_RPC"
  version = "0.1.0"

[[bin]]
  name = "server"
  path = "src/server.rs"

[[bin]]
  name = "client"
  path = "src/client.rs"

[dependencies]
  prost       = "0.11.9"
  prost-types = "0.11.9"
  tokio       = {version = "1.41.1", features = ["macros", "rt-multi-thread"]}
  tonic       = "0.9.2"

[build-dependencies]
  tonic-build = "0.9.2"
