[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3

[package]
  edition = "2021"
  name    = "p20_custom_error_types"
  version = "0.1.0"


[dependencies]
  thiserror = "2.0.0"

[[bin]]
  name = "main"
  path = "src/main.rs"
