[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[package]
name = "p20_custom_error_types"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror = "1.0.43"

[[bin]]
name = "main"
path = "src/main.rs"
