[package]
  edition = "2021"
  name    = "bin_web"
  version = "0.1.0"

[lib]
  crate-type = ["cdylib", "rlib"]

[dependencies]
  actix-files              = {version = "0.6.6", optional = true}
  actix-web                = {version = "4.9.0", optional = true, features = ["macros"]}
  cfg-if                   = {workspace = true}
  console_error_panic_hook = "0.1.7"
  env_logger               = {workspace = true}
  leptos                   = {version = "0.6.5", features = ["nightly"]}
  leptos_actix             = {version = "0.6.5", optional = true}
  leptos_meta              = {version = "0.6.5", features = ["nightly"]}
  leptos_router            = {version = "0.6.5", features = ["nightly"]}
  lib_adder                = {path = "../lib_adder"}
  lib_repo                 = {path = "../lib_repo"}
  log                      = {workspace = true}
  serde                    = {workspace = true}
  uuid                     = "1.11.0"
  wasm-bindgen             = "=0.2.95"

[features]
  csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]
  hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
  ssr = [
    "dep:actix-files",
    "dep:actix-web",
    "dep:leptos_actix",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
  ]

[profile.wasm-release]
  codegen-units = 1
  inherits      = "release"
  lto           = true
  opt-level     = 'z'
  panic         = "abort"

  [package.metadata.leptos]
    assets-dir           = "assets"
    bin-default-features = false
    bin-features         = ["ssr"]
    #bin-target-triple    = "aarch64-unknown-linux-gnu"
    browserquery         = "defaults"
    end2end-cmd          = "npx playwright test"
    end2end-dir          = "end2end"
    env                  = "DEV"
    lib-default-features = false
    lib-features         = ["hydrate"]
    lib-profile-release  = "wasm-release"
    output-name          = "bin_web"
    reload-port          = 3001
    site-addr            = "127.0.0.1:3000"
    site-pkg-dir         = "pkg"
    site-root            = "target/site"
    style-file           = "style/main.scss"
