[package]
  edition = "2024"
  name    = "runner"
  version = "0.1.0"

[dependencies]
  domain      = {path = "../domain"}
  application = {path = "../application"}
  adapters    = {path = "../adapters"}
  infra       = {path = "../infra"}
