[package]
  authors = ["mingyuchoo <mingyuchoo@gmail.com>"]
  edition = "2021"
  name    = "juniper_v014_mysql"
  version = "2.0.0"

[dependencies]
  actix-web  = "4.9"
  dotenv     = "0.15"
  env_logger = "0.11.5"
  juniper    = "0.16"
  log        = "0.4.22"
  mysql      = "25.0.1"
  openssl    = {version = "0.10", features = ["vendored"]}
  r2d2       = "0.8"
  r2d2_mysql = "25.0"
  serde      = {version = "1.0", features = ["derive"]}
  serde_json = "1.0"
  uuid       = {version = "1.11", features = ["serde", "v4"]}

[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3
