[package]
  edition = "2024"
  name    = "lib-api"
  version = "0.1.0"

[dependencies]
  actix-web         = "4.9.0"
  actix-web-lab     = "0.20.2"
  anyhow            = "1.0.95"
  chrono            = {features = ["clock"], version = "0.4.38"}
  jsonwebtoken      = "9.3.0"
  lib-db            = {path = "../lib-db", version = "0.1.0"}
  lib-index         = {path = "../lib-index", version = "0.1.0"}
  log               = "0.4.22"
  once_cell         = "1.20.2"
  reqwest           = {features = ["json", "stream"], version = "0.12.7"}
  serde             = {features = ["derive"], version = "1.0.215"}
  serde_json        = "1.0.133"
  surrealdb         = "2.1.2"
  thiserror         = "2.0.3"
  tokio             = {features = ["rt-multi-thread", "macros", "fs"], version = "1.39.3"}
  utoipa            = {features = ["actix_extras", "chrono", "macros"], version = "5.4.0"}
  utoipa-swagger-ui = {features = ["actix-web"], version = "9.0.2"}
  uuid              = {features = ["v4"], version = "1.10.0"}
