[package]
  edition = "2024"
  name    = "lib-api"
  version = "0.1.0"

[dependencies]
  actix-web   = "4.9.0"
  actix-web-lab = "0.20.2"
  lib-db      = {version = "0.1.0", path = "../lib-db"}
  log         = "0.4.22"
  serde       = {version = "1.0.215", features = ["derive"]}
  serde_json  = "1.0.133"
  thiserror   = "2.0.3"
  reqwest     = { version = "0.12.7", features = ["json", "stream"] }
  jsonwebtoken = "9.3.0"
  chrono      = { version = "0.4.38", features = ["clock"] }
  once_cell   = "1.20.2"
  anyhow      = "1.0.95"
