[package]
  edition = "2021"
  name    = "leptos-tutorial"
  version = "0.1.0"

[dependencies]
  console_error_panic_hook = "0.1.7"
  leptos                   = {version = "0.6.15", features = ["csr", "nightly"]}
  leptos_meta              = {version = "0.6.15", features = ["csr", "nightly"]}
