[package]
  edition = "2024"
  name    = "leptos-tutorial"
  version = "0.1.0"

[dependencies]
  console_error_panic_hook = "0.1.7"
  console_log              = "1.0.0"
  gloo-net                 = "0.6.0"
  gloo-timers              = {version = "0.3.0", features = ["futures"]}
  leptos                   = {version = "0.6.15", features = ["csr", "nightly"]}
  leptos_meta              = {version = "0.6.15", features = ["csr", "nightly"]}
  leptos_router            = {version = "0.6.15", features = ["csr"]}
  log                      = "0.4.22"
  serde                    = {version = "1.0.215", features = ["derive"]}
  serde_json               = "1.0.132"
  uuid                     = {version = "1.11.0", features = ["v4"]}
  web-sys                  = {version = "0.3.72", features = ["Document", "Window"]}

[profile.release]
  codegen-units = 1
  lto           = true
  opt-level     = 'z'
  panic         = "abort"
