attr_value_brace_style = "WhenRequired"           # "Always", "AlwaysUnlessLit", "WhenRequired" or "Preserve"
closing_tag_style      = "Preserve"               # "Preserve", "SelfClosing" or "NonSelfClosing"
indentation_style      = "Auto"                   # "Tabs", "Spaces" or "Auto"
macro_names            = ["leptos::view", "view"] # Macro names which will be formatted
max_width              = 100                      # Maximum width of each line
newline_style          = "Auto"                   # "Unix", "Windows" or "Auto"
tab_spaces             = 4                        # Number of spaces per tab

# Attribute values can be formatted by custom formatters
# Every attribute name may only select one formatter (this might change later on)
[attr_values]
  class = "Tailwind" # "Tailwind" is the only attribute value formatter available for now
