services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: azure-foundry-embedding-demo
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME:-text-embedding-3-large}
      - DATABASE_URL=sqlite:///app/data/embeddings.db
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
    volumes:
      - app-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app-data:
    driver: local
