[package]
name = "async_graphql_v40"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "4.0"
async-graphql-actix-web = "4.0"
actix-web = "4"

diesel = { version = "2.0.0", features = ["postgres"] }

