[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3

[package]
  edition = "2024"
  name    = "single_thread_http_server"
  version = "0.1.0"


[dependencies]
