[package]
name = "rust-sam-app"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = { version = "0.8.1", default-features = false, features = ["apigw_rest"] }
lambda_runtime = "0.8.1"
serde = "1.0.177"
serde_json = "1.0.104"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }

[[bin]]
name = "post_hello_world_function"
path = "src/post_hello_world.rs"

[[bin]]
name = "get_hello_world_function"
path = "src/get_hello_world.rs"
