[profile.dev]
  codegen-units = 256
  debug         = true
  incremental   = true
  opt-level     = 1

[profile.release]
  codegen-units = 1
  debug         = false
  lto           = "thin"
  opt-level     = 3

[package]
  edition = "2024"
  name    = "rust-sam-app"
  version = "0.1.0"

[dependencies]
  lambda_http        = {version = "0.13.0", default-features = false, features = ["apigw_rest"]}
  lambda_runtime     = "0.13.0"
  serde              = "1.0.214"
  serde_json         = "1.0.132"
  tokio              = {version = "1.44.2", features = ["macros"]}
  tracing            = {version = "0.1.40", features = ["log"]}
  tracing-subscriber = {version = "0.3.18", default-features = false, features = ["fmt"]}

[[bin]]
  name = "post_hello_world_function"
  path = "src/post_hello_world.rs"

[[bin]]
  name = "get_hello_world_function"
  path = "src/get_hello_world.rs"
