chain_width = 0
edition = "2021"
fn_params_layout = "Vertical"
format_code_in_doc_comments = true
imports_indent = "Visual"
imports_layout = "Vertical"
indent_style = "Visual"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
imports_granularity="Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
spaces_around_ranges = true
struct_field_align_threshold = 20
trailing_comma = "Always"
wrap_comments = true