[tasks.clean]
  args    = ["clean"]
  command = "cargo"

[tasks.clippy]
  args    = ["clippy"]
  command = "cargo"

[tasks.check]
  args    = ["check"]
  command = "cargo"

[tasks.format]
  args          = ["fmt"]
  command       = "cargo"
  dependencies  = ["check", "clippy"]
  install_crate = "rustfmt"

[tasks.build]
  args         = ["build", "--profile", "dev"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.release]
  args         = ["build", "--profile", "release"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.test]
  args         = ["test"]
  command      = "cargo"
  dependencies = ["format"]

[tasks.run]
  args         = ["run"]
  command      = "cargo"
  dependencies = ["format"]

# 워크스페이스 기본 태스크가 각 멤버에서 같은 태스크를 찾는 동작을 우회하기 위해
# 루트에서 서버 크레이트만 실행하도록 사용자 정의 workspace 태스크를 추가합니다.
# 이렇게 하면 `cargo make run`이 내부적으로 실행하는 workspace 단계가 이 태스크를 사용합니다.
[tasks.workspace]
  command = "cargo"
  args    = ["run", "-p", "bin-main"]
