[package]
  authors = ["Mingyu Choo <mingyuchoo@gmail.com>"]
  edition = "2021"
  name    = "diesel_postgres_init"
  version = "0.3.0"

[dependencies]
  diesel  = {version = "2.2.5", features = ["postgres"]}
  dotenvy = "0.15.7"

[profile.dev]
  debug     = true
  opt-level = 0

[profile.release]
  debug     = false
  opt-level = 3
