[package]
name = "presentation-backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "presentation_backend"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }
infrastructure = { path = "../infrastructure" }
serde = { workspace = true }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
uuid = { workspace = true }
tokio = { workspace = true }