[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[package]
name = "aws_sdk_dynamodb_v028"
version = "0.1.0"
edition = "2021"


[dependencies]
aws-config = "1.5.10"
aws-sdk-dynamodb = "1.53.0"
tokio = { version = "1.41.1", features = ["full"] }
