[package]
  edition = "2021"
  name    = "actix_surreal"
  version = "0.1.0"

[dependencies]
  actix-web  = "4.9.0"
  faker_rand = "0.1.1"
  rand       = "0.8.5"
  serde      = {version = "1.0.214", features = ["derive"]}
  surrealdb  = "2.0.4"
  thiserror  = "2.0.1"
